### PR TITLE
Ensure default methods can be invoked.

### LINKED ISSUE #1514: java.lang.IllegalAccessException with interface default method
Hello!

I have this:

    public interface LivestreamsApi {

        @GET("api/livestreams")
        Call<LivestreamsContainer> getLivestreams(@Query("limit") int limit);

        default Call<LivestreamsContainer> getLivestreams() {
            return getLivestreams(100);
        }
    }

Executing the method with the Query param works. But running the default method doesn't work. It says: http://pastebin.com/V8xGSF5K
When I add for (whatever reason?) `throws Exception` to the default method it now only says: http://pastebin.com/pZaEd0v0
But how to solve this exception and why do I have to add the `throws`?

Thanks in advance!
RandomByte

### PR DESCRIPTION
**Pull request by JakeWharton**
Because the service interface might not be public, we need to use a MethodHandle lookup means that ignores visibility.

Closes #1514.

### CODE REVIEW

File: retrofit/src/main/java/retrofit2/Platform.java [hunk 1]
```diff
@@ -70,8 +71,11 @@ Object invokeDefaultMethod(Method method, Class<?> declaringClass, Object object
 
     @Override Object invokeDefaultMethod(Method method, Class<?> declaringClass, Object object,
         Object... args) throws Throwable {
-      return MethodHandles.lookup()
-          .in(declaringClass)
+      // Because the service interface might not be public, we need to use a MethodHandle lookup
```
Comment (swankjesse) [inline retrofit/src/main/java/retrofit2/Platform.java]: Why wouldn't it be public? Strange

File: retrofit/src/test/java/retrofit2/Java8DefaultMethodsTest.java [hunk 2]
```diff
@@ -0,0 +1,27 @@
...
+  //  server.enqueue(new MockResponse().setBody("Hi"));
+  //
+  //  Retrofit retrofit = new Retrofit.Builder()
+  //      .baseUrl(server.url("/"))
+  //      .addConverterFactory(new ToStringConverterFactory())
+  //      .build();
+  //  Example example = retrofit.create(Example.class);
+  //
+  //  Response<String> response = example.user().execute();
+  //  assertThat(response.body()).isEqualTo("Hi");
```
Comment (swankjesse) [inline retrofit/src/test/java/retrofit2/Java8DefaultMethodsTest.java]: also call user() ?

**Comment by swankjesse** [comment]
LGTM

File: retrofit/src/main/java/retrofit2/Platform.java (hunk 1 above)
Comment (JakeWharton) [inline retrofit/src/main/java/retrofit2/Platform.java]: Don't know. Our tests and samples all use package-scoped interfaces though.
