### PR TITLE
Gracefully handle parse failure with locking

### LINKED ISSUE #4113: Object cannot be cast to class retrofit2.ServiceMethod
I ran into this with Retrofit 2.10.

```
java.lang.ClassCastException: class java.lang.Object cannot be cast to class retrofit2.ServiceMethod (java.lang.Object is in module java.base of loader 'bootstrap'; retrofit2.ServiceMethod is in unnamed module of loader 'app')
	at retrofit2.Retrofit.loadServiceMethod(Retrofit.java:246)
	at retrofit2.Retrofit$1.invoke(Retrofit.java:177)
	at jdk.proxy3/jdk.proxy3.$Proxy139.addPullRequestLabel(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at misk.client.ClientInvocationHandler.invoke(ClientInvocationHandler.kt:125)
	at jdk.proxy3/jdk.proxy3.$Proxy139.addPullRequestLabel(Unknown Source)
	at com.squareup.cash.treelot.github.PullRequestMaker.addLabels(PullRequestMaker.kt:237)
```

### PR DESCRIPTION
**Pull request by JakeWharton**
Before we would poison the map with the lock object so the second caller would get a weird ClassCastException.

Closes #4113 

---

- [x] `CHANGELOG.md`'s "Unreleased" section has been updated, if applicable.

### CODE REVIEW

File: retrofit/src/main/java/retrofit2/Retrofit.java [hunk 1]
```diff
@@ -212,38 +212,53 @@ private void validateServiceInterface(Class<?> service) {
...
+            // On successful lock insertion, perform the work and update the map before releasing.
+            // Other threads may be waiting on lock now and will expect the parsed model.
+            ServiceMethod<Object> result;
+            try {
+              result = ServiceMethod.parseAnnotations(this, service, method);
+            } catch (Throwable e) {
+              // Remove the lock on failure. Any other locked threads will retry as a result.
+              serviceMethodCache.remove(method);
+              throw e;
+            }
```
Comment (JakeWharton) [inline retrofit/src/main/java/retrofit2/Retrofit.java:240]: Change is here

File: retrofit/src/main/java/retrofit2/Retrofit.java [hunk 2]
```diff
@@ -212,38 +212,53 @@ private void validateServiceInterface(Class<?> service) {
...
+      // the lock. Once we can take the lock, the map is guaranteed to contain the model or null.
+      // Note: There's a chance that our effort to put a lock into the map has actually returned a
+      // finished model instead of a lock. In that case this code will perform a pointless lock and
+      // redundant lookup in the map of the same instance. This is rare, and ultimately harmless.
+      synchronized (lookup) {
+        Object result = serviceMethodCache.get(method);
+        if (result == null) {
+          // The other thread failed its parsing. We will retry (and probably also fail).
+          continue;
+        }
```
Comment (JakeWharton) [inline retrofit/src/main/java/retrofit2/Retrofit.java:259]: And here (plus the enclosing `while (true)`)

**Review by swankjesse — APPROVED** [review]

File: retrofit/src/main/java/retrofit2/Retrofit.java (hunk 2 above)
Comment (Endeavour233) [reply retrofit/src/main/java/retrofit2/Retrofit.java:259]: I am thinking about whether this situation is possible: `thread 1` put its `lock1`to the cache, granted the right to parse the method, but failed and threw an exception. Then, `thread 2`, which was waiting for `thread 1`  to parse the method, synchronize `lock1` successfully, find the `result` is null, continue the while loop and put its `lock2` to the cache. Then, `Thread 3` synchronize `lock1`. However, the `result` retrieved from the cache by `thread 3` is `lock2` instead of `null`. Thus, `thread 3` try to cast object to ServiceMethod and a `ClassCastException` happens. Can we check `result instanceof ServiceMethod<?>` here? What's more, can we check `lookup instanceof ServiceMethod<?>` before synchronize `lookup` to eliminate the pointless lock and redundant lookup you've metioned in comment(line 253)? Thanks.
