### PR TITLE
Fatal errors should crash the dispatcher thread

### LINKED ISSUE #2994: BodyObservable: AssertionError: This should never happen! Report as a bug with the full stacktrace.
Crash reported in wild

```
12-19 12:42:26.859 15627 15794 W System.err: io.reactivex.exceptions.UndeliverableException: java.lang.AssertionError: This should never happen! Report as a bug with the full stacktrace.
12-19 12:42:26.860 15627 15794 W System.err: 	at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
12-19 12:42:26.860 15627 15794 W System.err: 	at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onError(BodyObservable.java:79)
12-19 12:42:26.860 15627 15794 W System.err: 	at retrofit2.adapter.rxjava2.CallEnqueueObservable$CallCallback.onResponse(CallEnqueueObservable.java:68)
12-19 12:42:26.860 15627 15794 W System.err: 	at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:123)
12-19 12:42:26.860 15627 15794 W System.err: 	at okhttp3.v$a.c(RealCall.java:153)
12-19 12:42:26.860 15627 15794 W System.err: 	at okhttp3.internal.b.run(NamedRunnable.java:32)
12-19 12:42:26.860 15627 15794 W System.err: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
12-19 12:42:26.860 15627 15794 W System.err: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
12-19 12:42:26.860 15627 15794 W System.err: 	at java.lang.Thread.run(Thread.java:761)
12-19 12:42:26.861 15627 15794 W System.err: Caused by: java.lang.AssertionError: This should never happen! Report as a bug with the full stacktrace.
12-19 12:42:26.861 15627 15794 W System.err: 	at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onError(BodyObservable.java:75)
12-19 12:42:26.861 15627 15794 W System.err: 	at java.lang.Thread.nativeCreate(Native Method)
12-19 12:42:26.861 15627 15794 W System.err: 	at java.lang.Thread.start(Thread.java:730)
12-19 12:42:26.862 15627 15794 W System.err: 	at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:941)
12-19 12:42:26.862 15627 15794 W System.err: 	at java.util.concurrent.ThreadPoolExecutor.ensurePrestart(ThreadPoolExecutor.java:1582)
12-19 12:42:26.862 15627 15794 W System.err: 	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:313)
12-19 12:42:26.862 15627 15794 W System.err: 	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:533)
12-19 12:42:26.862 15627 15794 W System.err: 	at java.util.concurrent.ScheduledThreadPoolExecutor.submit(ScheduledThreadPoolExecutor.java:635)
12-19 12:42:26.862 15627 15794 W System.err: 	at rx.internal.schedulers.NewThreadWorker.scheduleActual(NewThreadWorker.java:246)
12-19 12:42:26.862 15627 15794 W System.err: 	at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker.schedule(CachedThreadScheduler.java:224)
12-19 12:42:26.862 15627 15794 W System.err: 	at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker.schedule(CachedThreadScheduler.java:214)
12-19 12:42:26.862 15627 15794 W System.err: 	at rx.internal.operators.SingleObserveOn$ObserveOnSingleSubscriber.onSuccess(SingleObserveOn.java:69)
12-19 12:42:26.862 15627 15794 W System.err: 	at rx.internal.util.ScalarSynchronousSingle$2$1.onSuccess(ScalarSynchronousSingle.java:140)
12-19 12:42:26.862 15627 15794 W System.err: 	at rx.internal.operators.SingleFromCallable.call(SingleFromCallable.java:48)
12-19 12:42:26.862 15627 15794 W System.err: 	at rx.internal.operators.SingleFromCallable.call(SingleFromCallable.java:29)
12-19 12:42:26.862 15627 15794 W System.err: 	at rx.Single.subscribe(Single.java:1979)
12-19 12:42:26.862 15627 15794 W System.err: 	at rx.internal.util.ScalarSynchronousSingle$2.call(ScalarSynchronousSingle.java:144)
12-19 12:42:26.862 15627 15794 W System.err: 	at rx.internal.util.ScalarSynchronousSingle$2.call(ScalarSynchronousSingle.java:124)
```

### PR DESCRIPTION
**Pull request by JakeWharton**
This is an imperfect fix as uncaught exceptions reaching OkHttpCall which are not fatal still only log, but most of the adapters are defending against anything getting this far already.

Also contained is a fix for the RxJava 2 async adapter. Non-200 responses delivered to the body observer would be forwarded to onError. If that callback threw a fatal exception, it would be re-delivered to the body observer despite it having already called a downstream terminal method. The fatal error should have been propagated by the async observer instead of attempting to make its way back downstream.

Closes #2994.

### CODE REVIEW

File: retrofit-adapters/rxjava2/src/test/java/retrofit2/adapter/rxjava2/AsyncTest.java [hunk 1]
```diff
@@ -46,14 +57,36 @@
...
+          @Override public void uncaughtException(Thread t, Throwable e) {
+            uncaughtExceptions.add(e);
+          }
+        });
+        return thread;
+      }
+    });
+
+    OkHttpClient client = new OkHttpClient.Builder()
+        .dispatcher(new Dispatcher(executorService))
```
Comment (swankjesse) [inline retrofit-adapters/rxjava2/src/test/java/retrofit2/adapter/rxjava2/AsyncTest.java]: neat
