### PR TITLE
Correct some Javadoc examples, always run Javadoc plugin.

### LINKED ISSUE #1351: No SNAPSHOT builds with new package name
The automatic SNAPSHOT deployment seems to be broken after #1342 . See https://travis-ci.org/square/retrofit/builds/95452176#L1793 for the Travis output/warnings.

### PR DESCRIPTION
**Pull request by JakeWharton**
Closes #1351.

### CODE REVIEW

File: retrofit/src/main/java/retrofit2/http/Field.java [hunk 1]
```diff
@@ -30,21 +30,22 @@
  * field pair for each non-{@code null} item.
  * <p>
  * Simple Example:
- * <pre>
+ * <pre>{@code
```
Comment (swankjesse) [inline retrofit/src/main/java/retrofit2/http/Field.java]: not sure if you want to bother, but Javadoc might format better with three spaces before `{@code` and a newline after it.

yes, this advice is ridiculous

Comment (JakeWharton) [inline retrofit/src/main/java/retrofit2/http/Field.java]: Hah. Do you know why? I'm inclined to believe you since Javadoc is ridiculous, but I checked the IDEA-rendered and HTML-rendered Javadoc and what's in this PR rendered correctly.

Comment (swankjesse) [inline retrofit/src/main/java/retrofit2/http/Field.java]: Sounds good to me. That format was obtained by Kevin B at one point by trial & error; things might work better with the latest Javadoc.
