### PR TITLE
Explicitly handle wrapped, re-thrown exceptions from onComplete, onError.

### LINKED ISSUE #2285: Retrofit + RxJava: Exception in onError crashes without stack trace
If exception is thrown in onError  (not intentionally) app crashes but stack trace is missing in logcat.

```
githubService.contributors("square", "retrofit")
        .subscribeOn(Schedulers.io())
        .observeOn(AndroidSchedulers.mainThread())
        .subscribe(new Subscriber<List<SimpleService.Contributor>>() {
            @Override
            public void onCompleted() {
            }

            @Override
            public void onError(Throwable e) {
                // Force java.lang.IndexOutOfBoundsException
                // App will crash, exception will be swollen (not visible in Logcat)
                int[] ints = new int[2];
                int intValue = ints[10];
            }

            @Override
            public void onNext(List<SimpleService.Contributor> contributors) {
            }
        });
```
While the same exception in plain RxJava leaves a stack trace in logcat.
```
Observable.error(new RuntimeException())
        .subscribeOn(Schedulers.io())
        .observeOn(AndroidSchedulers.mainThread())
        .subscribe(new Subscriber<Object>() {
            @Override
            public void onCompleted() {
            }

            @Override
            public void onError(Throwable throwable) {
                // Force java.lang.IndexOutOfBoundsException
                // App will crash, exception is visible in Logcat
                int[] ints = new int[2];
                int intValue = ints[10];
            }

            @Override
            public void onNext(Object o) {
            }
        });
```
Full examples available [here](https://github.com/AndrazP/onErrorExceptionSample). I'm not sure if this is a Retrofit issue or RxJava/RxAndroid, but would be thankful if you can help me out. It's nearly impossible to debug such unintentional exceptions without stack trace.

### PR DESCRIPTION
**Pull request by JakeWharton**
Because `Exceptions.throwIfFatal` treats these as fatal, prior to this they would bubble up to the caller. This is either the thread uncaught exception handler which is fine, but in the case of async sources it would go to the library code invoking the async callback (like OkHttp's `Call`) which might swallow them.

Tests are just copy/paste from RxJava 2 adapter.

Closes #2285.

### CODE REVIEW

File: retrofit-adapters/rxjava/src/test/java/retrofit2/adapter/rxjava/CompletableThrowingSafeSubscriberTest.java [hunk 1]
```diff
@@ -0,0 +1,129 @@
...
+
+  @Test public void throwingInOnCompleteDeliveredToPlugin() {
+    server.enqueue(new MockResponse());
+
+    final AtomicReference<Throwable> pluginRef = new AtomicReference<>();
+    RxJavaPlugins.getInstance().registerErrorHandler(new RxJavaErrorHandler() {
+      @Override public void handleError(Throwable throwable) {
+        if (throwable instanceof OnCompletedFailedException) {
+          if (!pluginRef.compareAndSet(null, throwable)) {
+            throw Exceptions.propagate(throwable); // Don't swallow secondary errors!
```
Comment (swankjesse) [inline retrofit-adapters/rxjava/src/test/java/retrofit2/adapter/rxjava/CompletableThrowingSafeSubscriberTest.java]: neat

File: retrofit-adapters/rxjava/src/test/java/retrofit2/adapter/rxjava/SingleThrowingTest.java [hunk 2]
```diff
@@ -0,0 +1,234 @@
...
+    service.result().subscribe(new ForwardingObserver<Result<String>>(observer) {
+      @Override public void onSuccess(Result<String> value) {
+        throw e;
+      }
+    });
+
+    assertThat(pluginRef.get()).isSameAs(e);
+  }
+
+  @Ignore("Single's contract is onNext|onError so we have no way of triggering this case")
```
Comment (swankjesse) [inline retrofit-adapters/rxjava/src/test/java/retrofit2/adapter/rxjava/SingleThrowingTest.java]: tricky
