### PR TITLE
igonre "isSynthetic" method when eagerly validating

### LINKED ISSUE #3863: service eager validation is failed when using jacoco
What kind of issue is this?
 - [x] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests
       get fixed. Here’s an example: https://gist.github.com/swankjesse/6608b4713ad80988cdc9

Jacoco is a world famous code coverage tool  . And it add $jacocoInit() method to interface in order to finish their job. 
But it could cause Retrofit failed in eager service validation. 
Should Retrofit eager validation ignore SYNTHETIC method in such scene ?

```
public final class Retrofit {
 private void validateServiceInterface(Class<?> service) {
............
    if (validateEagerly) {
      Platform platform = Platform.get();
      for (Method method : service.getDeclaredMethods()) {
        if (!platform.isDefaultMethod(method) && !Modifier.isStatic(method.getModifiers())) {
          loadServiceMethod(method);
        }
      }
    }
  ...........
}
```

### PR DESCRIPTION
**Pull request by pkxiuluo**
Closes #3863

### CODE REVIEW

File: retrofit/src/main/java/retrofit2/Retrofit.java [hunk 1]
```diff
@@ -191,7 +191,8 @@ private void validateServiceInterface(Class<?> service) {
     if (validateEagerly) {
       Platform platform = Platform.get();
       for (Method method : service.getDeclaredMethods()) {
-        if (!platform.isDefaultMethod(method) && !Modifier.isStatic(method.getModifiers())) {
+        if (!platform.isDefaultMethod(method) && !Modifier.isStatic(method.getModifiers())
+          && !method.isSynthetic()) {
```
Comment (JakeWharton) [inline retrofit/src/main/java/retrofit2/Retrofit.java:195]:
```suggestion
        if (!platform.isDefaultMethod(method)
            && !Modifier.isStatic(method.getModifiers())
            && !method.isSynthetic()) {
```

**Comment by JakeWharton** [comment]
I decided I can live without a test.

**Comment by Goooler** [comment]
Need to solve conflicts.
