### PR TITLE
Account for static interface methods

### LINKED ISSUE #2032: Support for Java8 interface static methods
Retrofit 2.1.0 currently throws an exception building a client implementation proxy if the interface has static methods.

### PR DESCRIPTION
**Pull request by ZacSweers**
Resolves #2032

Not able to add a test though since it's java 7

### CODE REVIEW

File: retrofit/src/main/java/retrofit2/Retrofit.java [hunk 1]
```diff
@@ -143,6 +144,8 @@
             }
             if (platform.isDefaultMethod(method)) {
               return platform.invokeDefaultMethod(method, service, proxy, args);
+            } else if (Modifier.isStatic(method.getModifiers())) {
```
Comment (hzsweers) [inline retrofit/src/main/java/retrofit2/Retrofit.java]: Let me know if you want this removed. It's weird to be calling a static method on an instance, but technically legal. This at least keeps that behavior

Comment (swankjesse) [reply retrofit/src/main/java/retrofit2/Retrofit.java]: Is this line reachable in test cases? I assume it won’t be dispatched this way

**Comment by JakeWharton** [comment]
Please duplicate `Java8DefaultMethodsTest` and update for this functionality. You can temporarily set the project to compile with 8 to run it and then comment it out once finished.

File: retrofit/src/main/java/retrofit2/Retrofit.java (hunk 1 above)
Comment (JakeWharton) [reply retrofit/src/main/java/retrofit2/Retrofit.java]: Yeah I don't think this can happen. The only case I can think of is if a virtual method was made static without recompiling the caller. But even then I would expect the VM to intervene.

Comment (ZacSweers) [reply retrofit/src/main/java/retrofit2/Retrofit.java]: done f1fbbda

**Comment by ZacSweers** [comment]
Updated the test in f6da87c. Also fixed an issue with it redeclaring a `response` variable along the way

File: retrofit/src/test/java/retrofit2/Java8DefaultMethodsTest.java [hunk 2]
```diff
@@ -34,12 +38,13 @@
   //  Retrofit retrofit = new Retrofit.Builder()
   //      .baseUrl(server.url("/"))
   //      .addConverterFactory(new ToStringConverterFactory())
+  //      .validateEagerly(true)
```
Comment (JakeWharton) [inline retrofit/src/test/java/retrofit2/Java8DefaultMethodsTest.java]: Can you move this to a separate test class? I don't want to conflate the two things being tested here together.

File: retrofit/src/main/java/retrofit2/Retrofit.java (hunk 1 above)
Comment (swankjesse) [reply retrofit/src/main/java/retrofit2/Retrofit.java]: Is the condition reachable?

Comment (swankjesse) [reply retrofit/src/main/java/retrofit2/Retrofit.java]: Ahh, this happens during reflection, not invocation. Works for me.
