### PR TITLE
Don't attempt to resolve Lookup ctor on API 24/25

### LINKED ISSUE #3343: Didn't find class "java.lang.invoke.MethodHandles$Lookup"
//retrofit
 ```
   implementation 'com.squareup.retrofit2:converter-moshi:2.8.0'
   implementation 'com.squareup.retrofit2:retrofit:2.8.0'
   implementation 'com.squareup.retrofit2:adapter-rxjava2:2.8.0'
   implementation 'com.squareup.retrofit2:converter-gson:2.8.0'
```

It doesn't work with either moshi either gson converters.

Gradle configured with

```
compileOptions {
        sourceCompatibility = 1.8
        targetCompatibility = 1.8
    }

kotlinOptions {
        jvmTarget = "1.8"
    }
```

Also tried

```
compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
```

What's the error?

>  Caused by: java.lang.ClassNotFoundException: Didn't find class "java.lang.invoke.MethodHandles$Lookup" 

It happens only on:
Android 7.0
Android 7.1.1
Android 7.1.2

Where does it print the stack trace?

https://github.com/square/retrofit/blob/master/retrofit/src/main/java/retrofit2/Platform.java 
Line 62, 115, 44, 34, 37, 430

### PR DESCRIPTION
**Pull request by JakeWharton**
Unfortunately we lack functional tests on Android. I'm going to remedy that separately.

Closes #3343

### CODE REVIEW

File: retrofit/src/test/java/retrofit2/DefaultMethodsAndroidTest.java [hunk 1]
```diff
@@ -0,0 +1,99 @@
...
+
+    try {
+      example.user();
+      fail();
+    } catch (UnsupportedOperationException e) {
+      assertThat(e).hasMessage("Calling default methods on API 24 and 25 is not supported");
+    }
+  }
+
+  @Config(sdk = 24)
```
Comment (swankjesse) [inline retrofit/src/test/java/retrofit2/DefaultMethodsAndroidTest.java]: 25?

**Comment by JakeWharton** [comment]
https://travis-ci.org/github/square/retrofit/builds/666522141
