### PR TITLE
Unify HttpException into a single shared type.

### LINKED ISSUE #2194: Promote HttpException to core artifact.
Change adapter implementations to be deprecated but extend it.

### PR DESCRIPTION
**Pull request by JakeWharton**
Closes #2195. Closes #2194.

### CODE REVIEW

File: retrofit/src/main/java/retrofit2/HttpException.java [hunk 1]
```diff
@@ -0,0 +1,52 @@
...
+ * Unless required by applicable law or agreed to in writing, software
+ * distributed under the License is distributed on an "AS IS" BASIS,
+ * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+package retrofit2;
+
+/** Exception for an unexpected, non-2xx HTTP response. */
+public class HttpException extends Exception {
```
Comment (NightlyNexus) [inline retrofit/src/main/java/retrofit2/HttpException.java]: I suppose this could have been final, and the deprecated types could have delegated to this.
probably not worth those extra lines, though.

File: retrofit/src/main/java/retrofit2/HttpException.java [hunk 2]
```diff
@@ -0,0 +1,52 @@
+/*
+ * Copyright (C) 2016 Square, Inc.
```
Comment (swankjesse) [inline retrofit/src/main/java/retrofit2/HttpException.java]: 2017 ?

File: retrofit/src/main/java/retrofit2/HttpException.java (hunk 1 above)
Comment (swankjesse) [inline retrofit/src/main/java/retrofit2/HttpException.java]: Probably can’t compose because `catch` clauses are expecting a specific type.

**Comment by swankjesse** [comment]
LGTM

File: retrofit/src/main/java/retrofit2/HttpException.java (hunk 2 above)
Comment (JakeWharton) [inline retrofit/src/main/java/retrofit2/HttpException.java]: Not actually a new type. Copied from one of the adapters.
